[package]
name = "wealth_manager"
authors = ["laurasalcido"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde="1.0.117"
serde_json="1.0.59"
chrono = "0.4.19"
rand = "0.8.5"